include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    avoid_redundant_argument_values: true
    use_super_parameters: true
    use_decorated_box: true
